#context.objects = [
#    {   factory = adapter
#        args = {
#            factory.name     = support.null-audio-sink
#            node.name        = "music"
#            media.class      = Audio/Sink
#            audio.position   = [ FL FR ]
#            monitor.channel-volumes = true
#            monitor.passthrough = true
#        }
#    }
#    {   factory = adapter
#        args = {
#            factory.name     = support.null-audio-sink
#            node.name        = "voip"
#            media.class      = Audio/Sink
#            audio.position   = [ FL FR ]
#            monitor.channel-volumes = true
#            monitor.passthrough = true
#        }
#    }
#    {   factory = adapter
#        args = {
#            factory.name     = support.null-audio-sink
#            node.name        = "game"
#            media.class      = Audio/Sink
#            audio.position   = [ FL FR ]
#            monitor.channel-volumes = true
#            monitor.passthrough = true
#        }
#    }
#    {   factory = adapter
#        args = {
#            factory.name     = support.null-audio-sink
#            node.name        = "other"
#            media.class      = Audio/Sink
#            audio.position   = [ FL FR ]
#            monitor.channel-volumes = true
#            monitor.passthrough = true
#        }
#    }
#]
context.exec = [
    { path = "bash" args = "/home/quat/git/pipewire-setup/pipewire-setup.sh" }
]
